# Generated by Django 3.0.2 on 2023-04-15 09:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='image',
            field=models.CharField(default='https://www.processmaker.com/wp-content/uploads/2021/06/no-code-scaled.jpg', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='updated_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 15, 9, 30, 46, 356799, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pages',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
